apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-api
  namespace: flask
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: flask-api.local
    http:
      paths:
      - path: /hello/
        pathType: Prefix
        backend:
          service:
            name: flask-api
            port:
              number: 80
